name: Cypress

on: [pull_request]

jobs:
  run-tests:
    strategy:
      matrix:
        browser: [firefox, chrome, edge]

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: '115.0esr'

      - uses: cypress-io/github-action@v6
        with:
          config: video=false
          browser: ${{ matrix.browser }}
          build: yarn build:test
